---

require:
  - rubocop-minitest
  - rubocop-rake

inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - test/allow_list_bench.rb

Layout/LineLength:
  Exclude:
    - examples/**/*.rb

Lint/SuppressedException:
  Exclude:
    - examples/**/*.rb
    - test/adapters/net_http_test.rb
    - test/helpers/circuit_breaker_helper.rb
    - test/helpers/resource_helper.rb
    - test/protected_resource_test.rb

Minitest/AssertPredicate:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false

Minitest/RefuteFalse:
  Enabled: false

Naming/InclusiveLanguage:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - ext/semian/extconf.rb

Style/NumericLiteralPrefix:
  EnforcedOctalStyle: zero_only

Style/RedundantConstantBase:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false
